import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ScrollToTop } from "@/components/globalcomponents";

// Noe Display font (for display/headings)
const noeDisplay = localFont({
  src: [
    {
      path: "../noe-display-fonts/NoeDisplay.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../noe-display-fonts/NoeDisplay-RegularItalic.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "../noe-display-fonts/fonnts.com-NoeDisplay-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../noe-display-fonts/Noe_Display_Medium_Italic.woff.woff",
      weight: "500",
      style: "italic",
    },
  ],
  variable: "--font-display",
  display: "swap",
  fallback: ["serif"],
});

// Satoshi font (for body text)
const satoshi = localFont({
  src: [
    {
      path: "../satoshi-fonts/Satoshi-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../satoshi-fonts/Satoshi-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "../satoshi-fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../satoshi-fonts/Satoshi-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../satoshi-fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../satoshi-fonts/Satoshi-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../satoshi-fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../satoshi-fonts/Satoshi-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../satoshi-fonts/Satoshi-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../satoshi-fonts/Satoshi-BlackItalic.woff2",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-body",
  display: "swap",
  fallback: ["system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${noeDisplay.variable} ${satoshi.variable} antialiased`}
      >
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
